// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jaoprddrylpcfiaaxtkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imphb3ByZGRyeWxwY2ZpYWF4dGtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzOTEwMzMsImV4cCI6MjA2Nzk2NzAzM30.pHQZBi_XdtSKn1IW4UcQCmDksonBIGRO656pEAfniFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY); 